// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGEBI.Infrastructure.Persistence;

#nullable disable

namespace SIGEBI.Infrastructure.Migrations
{
    [DbContext(typeof(SIGEBIDbContext))]
    [Migration("20260619180000_AgregarModuloPrestamosFinal")]
    partial class AgregarModuloPrestamosFinal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGEBI.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Devolucion", b =>
                {
                    b.Property<int>("IdDevolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDevolucion"));

                    b.Property<string>("CondicionLibro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPrestamo")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDevolucion");

                    b.HasIndex("IdPrestamo");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AnioPublicacion")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("CopiasDisponibles")
                        .HasColumnType("int");

                    b.Property<int>("CopiasTotales")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NombreAutor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrestamoIdPrestamo")
                        .HasColumnType("int");

                    b.Property<int?>("SolicitudIdSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ISBN");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("PrestamoIdPrestamo");

                    b.HasIndex("SolicitudIdSolicitud");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioIdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdNotificacion");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Penalizacion", b =>
                {
                    b.Property<int>("IdPenalizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPenalizacion"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Monto")
                        .HasColumnType("float");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<string>("UsuarioIdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPenalizacion");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Penalizaciones");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestamo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.RegistroAuditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadAfectada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAuditoria");

                    b.ToTable("RegistroAuditorias");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuarioSolicitante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReporte");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Resolucion", b =>
                {
                    b.Property<int>("IdResolucion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResolucion"));

                    b.Property<DateTime>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdBibliotecario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("TipoResolucion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("IdResolucion");

                    b.HasIndex("IdBibliotecario");

                    b.HasIndex("IdSolicitud")
                        .IsUnique();

                    b.ToTable("Resoluciones");

                    b.HasDiscriminator<string>("TipoResolucion").HasValue("Resolucion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioIdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("TipoUsuario").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Aprobacion", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Resolucion");

                    b.Property<int?>("IdPrestamoGenerado")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoGeneradoIdPrestamo")
                        .HasColumnType("int");

                    b.HasIndex("PrestamoGeneradoIdPrestamo");

                    b.HasDiscriminator().HasValue("Aprobacion");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Rechazo", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Resolucion");

                    b.Property<string>("MotivoRechazo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Rechazo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Auditor", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("Auditor");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Docente", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Usuario");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Docente");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Estudiante", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Usuario");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Estudiante");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.PersonalBibliotecario", b =>
                {
                    b.HasBaseType("SIGEBI.Domain.Entities.Usuario");

                    b.HasDiscriminator().HasValue("PersonalBibliotecario");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Devolucion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("IdPrestamo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Libro", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("SIGEBI.Domain.Entities.Prestamo", null)
                        .WithMany("Libros")
                        .HasForeignKey("PrestamoIdPrestamo");

                    b.HasOne("SIGEBI.Domain.Entities.Solicitud", null)
                        .WithMany("LibrosSolicitados")
                        .HasForeignKey("SolicitudIdSolicitud");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Usuario", null)
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Penalizacion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Penalizaciones")
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamo", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Resolucion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Usuario", "Bibliotecario")
                        .WithMany()
                        .HasForeignKey("IdBibliotecario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGEBI.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("Resolucion")
                        .HasForeignKey("SIGEBI.Domain.Entities.Resolucion", "IdSolicitud")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bibliotecario");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioIdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Aprobacion", b =>
                {
                    b.HasOne("SIGEBI.Domain.Entities.Prestamo", "PrestamoGenerado")
                        .WithMany()
                        .HasForeignKey("PrestamoGeneradoIdPrestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrestamoGenerado");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Prestamo", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("LibrosSolicitados");

                    b.Navigation("Resolucion")
                        .IsRequired();
                });

            modelBuilder.Entity("SIGEBI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Notificaciones");

                    b.Navigation("Penalizaciones");

                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
